version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pj_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photo_journal

    volumes:
      - ./.db:/var/lib/postgresql/data
